name: Bechmark

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  bench:
    name: Bechmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v4
      - if: matrix.benchmark == 'ouch'
        name: Install ouch
        run: |-
          wget https://github.com/ouch-org/ouch/releases/latest/download/ouch-x86_64-unknown-linux-gnu.tar.gz
          tar --extract --file ouch-x86_64-unknown-linux-gnu.tar.gz
          install -D --no-target-directory --verbose ouch-x86_64-unknown-linux-gnu/ouch ~/.local/bin/ouch
          echo ~/.local/bin >> "$GITHUB_PATH"
      - name: Install Dependencies
        run: rye sync --no-lock
      - if: matrix.benchmark == 'ouch'
        name: Prepare Benchmark
        run: bash scripts/prepare.sh
      - name: Run Benchmark
        run: |-
          source .venv/bin/activate
          mkdir --parents --verbose results/
          python src/bench/${{ matrix.benchmark }}.py --output results/${{ matrix.benchmark }}.md
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.benchmark }}
          path: results/
    strategy:
      matrix:
        benchmark:
          - cksum
          - ouch

  upload:
    name: Upload
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - bench
    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          path: results/
          merge-multiple: true
      - name: Upload to GitHub Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: bench
          publish_dir: results/
          force_orphan: true
