name: Bechmark

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  bench:
    name: Bechmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v4
      - name: Install ouch
        run: |-
          brew update
          brew install ouch
      - name: Install Dependencies
        run: rye sync --no-lock
      - name: Run Benchmarks
        run: |-
          source .venv/bin/activate
          mkdir --parents --verbose results/
          python src/bench/${{ matrix.benchmark }}.py --output results/${{ matrix.benchmark }}.md
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.benchmark }}
          path: results/
    strategy:
      matrix:
        benchmark:
          - cksum
          - ouch

  upload:
    name: Upload
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - bench
    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          path: results/
          merge-multiple: true
      - name: Upload to GitHub Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: bench
          publish_dir: results/
          force_orphan: true
