name: Bechmark

on:
  push:

jobs:
  bench:
    name: Bechmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: requirements-dev.lock
      - name: Install ouch
        run: |-
          wget https://github.com/ouch-org/ouch/releases/latest/download/ouch-x86_64-unknown-linux-gnu.tar.gz
          tar --extract --file ouch-x86_64-unknown-linux-gnu.tar.gz
          install -D --no-target-directory --verbose ouch-x86_64-unknown-linux-gnu/ouch ~/.local/bin/ouch
          echo ~/.local/bin >> "$GITHUB_PATH"
      - name: Install Dependencies
        run: pip install --requirement requirements-dev.lock
      - name: Prepare Benchmark
        run: bash scripts/prepare.sh
      - name: Run Benchmark
        run: |-
          python src/bench/cksum.py
          python src/bench/ouch.py
          mkdir --parents --verbose results/
          cp docs/{cksum,ouch}.md results/
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/

  upload:
    name: Upload
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - bench
    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          name: results
          path: results/
      - name: Upload to GitHub Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_branch: bench
          publish_dir: results/
          force_orphan: true

  docs:
    name: Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - bench
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: requirements-dev.lock
      - name: Install Dependencies
        run: pip install --requirement requirements-dev.lock
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          name: results
          path: docs/
      - name: Build Docs
        run: mkdocs build
      - if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --no-history
